spring.datasource.url=	jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=bABkMscKtSlGjBsuaQicTuooRNLcYMGS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

mailjet.api.public=21fdacbee58ae9051ecc57ce38578ef9
mailjet.api.secret=2fe0edd871e3df06dc8db917a33aaad2
mailjet.from.email=no-reply@ezvous.app
mailjet.from.name=EzVous